# mkdocs.yml
site_url: https://wHkr.github.io/Bakeology/
site_name: Bakeology
nav:
  - Home: index.md
  - About: about.md
  - Cakes: cakes.md
  - Pastries: pastries.md
  - Breads: breads.md
  - Gallery: gallery.md
  - Contact: contact.md
theme:
  name: material
  favicon: img/icons/bakeology.jpg # No leading '/'
  logo: img/icons/logo.png # '/'; indicates to start from root
 # palette: Light and Dark settings button - Missing a dependency
    # Dark Mode
  #  - scheme: slate
  #    toggle:
  #      icon: material/weather-sunny
  #      name: Dark mode
  #      primary: deep orange
  #      accent: deep purple
  #    # Light Mode
  #  - scheme: default
   #   toggle:
   #     icon: material/weather-night
   #     name: Light mode
   #     primary: blue
   #     accent: deep orange
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.path
    - navigation.top
    - search.highlight
    - search.suggest
extra_css:
  - stylesheets/extra.css