# mkdocs.yml
site_url: https://wHkr.github.io/Bakeology/
site_name: Bakeology
nav:
  - Home: index.md
  - About: about.md
  - Cakes: cakes.md
  - Pastries: pastries.md
  - Breads: breads.md
  - Gallery: gallery.md
  - Contact: contact.md
theme:
  name: material
  favicon: img/icons/bakeology.jpg # No leading '/'
  logo: img/icons/logo.png # '/'; indicates to start from root
  features:
    #- header.autohide # Hides header after scrolling down
    - navigation.instant # Internal links wont be totally reloaded - Saves time
    - navigation.instant.progress # Loading indicator
    #- navigation.tabs # Nav tabs on header under the name
    #- navigation.tabs.sticky # Nav tabs lock below the header
    #- navigation.path # Breadcrumbs above title of each page
    - navigation.top # Back to top button after scrolling down
    - search.highlight
    - search.suggest
extra_javascript:
  - javascripts/extra.js
extra_css:
  - stylesheets/extra.css